# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    url: projects/
    weight: 11
  - name: Publications
    url: /#publications
    weight: 12
  - name: News
    url: /#news
    weight: 13
  # - name: Students
  #   url: students/
  #   weight: 14
  # - name: Courses
  #   url: courses/
  #   weight: 15
  # - name: Operating Systems
  #   parent: Teaching
  #   url: courses/operatingsystem
  #   weight: 10  
  # - name: Big Data Storage
  #   parent: Teaching
  #   url: courses/bigdatastorage
  #   weight: 11
  # - name: Academic Resources
  #   url: library/
    # weight: 16
  - name: Contact
    url: /#contact
    weight: 17
